name: Flutter Build APK From Zip

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Menggunakan nama file zip baru Anda yang telah di-rename
    - name: Extract Project Zip
      run: |
        unzip audit_stock_opname.zip -d extracted_project
        echo "=== Isi folder setelah diekstrak ==="
        ls -la extracted_project

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get dependencies
      run: |
        PROJ_DIR=$(find extracted_project -name "pubspec.yaml" -exec dirname {} \;)
        cd $PROJ_DIR
        flutter pub get

    - name: Build APK
      run: |
        PROJ_DIR=$(find extracted_project -name "pubspec.yaml" -exec dirname {} \;)
        cd $PROJ_DIR
        flutter build apk --debug --no-pub

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: "**/build/app/outputs/flutter-apk/*.apk"
